max_width = 80
use_small_heuristics = "Max"
newline_style = "Unix"
format_strings = true
format_code_in_doc_comments = true
use_field_init_shorthand = true
normalize_comments = true
wrap_comments = true
comment_width = 100

